# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 086ee138dd31c6f495f2c09084d81b80a607c50fc1c5f950b7bf7009da7caf39d13b32cf32efe4780a9e378a770a6ebf5947f40135f104f96413f5ab53fb1f37

test:
  secret_key_base: e87d32ad21c3ead2ff0e509794424de4d66ad2ea46fb1a5e5c30869606773805ffb27bb8bc29acd6a348b6a6d35b8cccc3cea90bf4e6f0adffa4769d2aa24b1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
